name: Generate Code Coverage and Upload to Coveralls

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      # Run tests and generate coverage
      - name: Run tests with coverage
        run: npm run test:coverage

      # Upload the entire coverage directory as an artifact
      - name: Upload coverage directory as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage/

      # Upload lcov.info to Coveralls
      - name: Upload coverage to Coveralls
        run: npm run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
