name: Run Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Generate coverage badge
        run: |
          npx coverage-badge --input ./coverage/lcov.info --output ./coverage/badge.svg

      - name: Upload coverage report and badge
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
